export const  ADD_INGREDIENT = 'ADD_INGREDIENT';
export const  REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const  SET_INGREDIENT = 'SET_INGREDIENT';
export const  SET_ERROR = 'SET_ERROR';

export const  PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const  PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const  PURCHASE_BURGER_START = 'PURCHASE_START';
export const  PURCHASE_HANDLED= 'PURCHASE_HANDLED';

export const  FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const  FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const  FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL';


export const  AUTH_START = 'AUTH_START';
export const  AUTH_SUCCESS = 'AUTH_SUCCESS';
export const  AUTH_FAIL = 'AUTH_FAIL';
export const  AUTH_LOGOUT = 'AUTH_LOGOUT';
export const  SET_AUTH_PATH= 'SET_AUTH_PATH';
